using OnlineRivalMarket.Domain.Dtos.FieldInformationDtos;

namespace OnlineRivalMarket.Application.Features.CompanyFeatures.FieldInformationFeatures.Queries.FieldInformationHome;
public sealed record FieldInformationHomeQueryResponse(IList<FieldInformationsesDto> Data);
