using OnlineRivalMarket.Application.Messaging;
namespace OnlineRivalMarket.Application.Features.AppFeatures.UserAndCompanyRLFeatures.Commands.RemoveByIdUserAndCompanyRL;
public sealed record RemoveByIdUserAndCompanyRLCommand(string Id) : ICommand<RemoveByIdUserAndCompanyRLCommandResponse>;