namespace OnlineRivalMarket.Application.Features.CompanyFeatures.IntelligenceRecordFeatures.Queries.GetFilteredIntelligenceRecordsAsync;
public sealed record IntelligenceRecordFilterResponse(IList<IntelligenceRecordDto> Data);
