namespace OnlineRivalMarket.Application.Features.CompanyFeatures.ForeignCurrency.Queries.GetAllForeignCurrency.GetAllForeignCurrency;
public sealed record GetAllForeignCurrencyResponse(IList<OnlineRivalMarket.Domain.CompanyEntities.ForeignCurrency> Data){ }
