namespace OnlineRivalMarket.Application.Features.CompanyFeatures.FieldInformationFeatures.Queries.FieldInformationById;
public sealed record FieldInformationByIdQueryResponse(IList<FieldInformationsesDto> Data );
