namespace OnlineRivalMarket.Domain.Repositories.CompanyDbContext.IntelligenceRecordRepository;
public interface  IIntelligenceRecordCommandRepository : ICompanyDbCommandRepository<IntelligenceRecord>{}
