namespace OnlineRivalMarket.Application.Features.CompanyFeatures.ForeignCurrency.Queries.GetAllForeignCurrency.GetAllForeignCurrencyDtoAsync;
public sealed record GetAllForeignCurrencyDtoQuery(string CompanyId) : IQuery<GetAllForeignCurrencyDtoQueryResponse>;

