namespace OnlineRivalMarket.Application.Features.CompanyFeatures.IntelligenceRecordFeatures.Queries.IntelligenceRecordDtos;
public sealed record IntelligenceRecordDtoQuery(string CompanyId) : IQuery<IntelligenceRecordDtoQueryResponse>;
