using OnlineRivalMarket.Domain.Repositories.CompanyDbContext.CampaignRepository;
using OnlineRivalMarket.Domain.Repositories.CompanyDbContext.CampaingImagesFileRepositories;

namespace OnlineRivalMarket.Application.Features.CompanyFeatures.CampaignFeaures.CampaignRules;
public class CampaignBusinessRule(ICampaignQueryRepository campaignQueryRepository)
{
}
